"""add_short_code_to_task

Revision ID: 2bac802bdbcc
Revises: c7e570125e2e
Create Date: 2026-06-10 00:11:21.478798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bac802bdbcc'
down_revision: Union[str, Sequence[str], None] = 'c7e570125e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('short_code', sa.String(length=16), nullable=False, server_default=''))
    op.create_index(op.f('ix_task_short_code'), 'task', ['short_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_short_code'), table_name='task')
    op.drop_column('task', 'short_code')
    # ### end Alembic commands ###
