"""add memory_fragment

Revision ID: bd57029e2c71
Revises: 117fed4588bb
Create Date: 2026-06-09 17:13:40.214375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'bd57029e2c71'
down_revision: Union[str, Sequence[str], None] = '117fed4588bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_fragment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatid', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_fragment_chatid'), 'memory_fragment', ['chatid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_fragment_chatid'), table_name='memory_fragment')
    op.drop_table('memory_fragment')
    # ### end Alembic commands ###
