"""add label to task_file

Revision ID: c7e570125e2e
Revises: bd57029e2c71
Create Date: 2026-06-09 17:52:32.715719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e570125e2e'
down_revision: Union[str, Sequence[str], None] = 'bd57029e2c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add as nullable first (existing rows have no label)
    op.add_column('task_file', sa.Column('label', sa.String(length=128), nullable=True))
    # Backfill empty string for existing rows
    op.execute("UPDATE task_file SET label = '' WHERE label IS NULL")
    # Now make it NOT NULL
    op.alter_column('task_file', 'label', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_file', 'label')
    # ### end Alembic commands ###
